### ISSUE TITLE
CUDA_VISIBLE_DEVICES=0 python train_search.py when we run this command getting error?

### ISSUE THREAD

**Issue by Naveennavik** [TAMU-VITA/FasterSeg#12]
Your work seem to be good enough to see but i have some doubts When i tried running the above command it showing error
Traceback (most recent call last):
  File "train_search.py", line 23, in <module>
    from datasets.cityscapes.cityscapes import Cityscapes
  File "/media/drive/2f08d5f1-1439-4edf-9bb4-1d19896475a5/Naveen/FasterSeg/tools/datasets/__init__.py", line 1, in <module>
    from .cityscapes import Cityscapes
  File "/media/drive/2f08d5f1-1439-4edf-9bb4-1d19896475a5/Naveen/FasterSeg/tools/datasets/cityscapes/__init__.py", line 1, in <module>
    from .cityscapes import Cityscapes
  File "/media/drive/2f08d5f1-1439-4edf-9bb4-1d19896475a5/Naveen/FasterSeg/tools/datasets/cityscapes/cityscapes.py", line 6, in <module>
    class Cityscapes(BaseDataset):
TypeError: module.__init__() takes at most 2 arguments (3 given)
May i know what is the reason for this error @chenwydj @TianlongChenTAMU

**Comment by chenwydj** [comment]
Hi @Naveennavik! Thank you for your interest in our work!

I just cloned my repo and tested it again, and the search script works. I did not meet your error.

Could you please make sure you are on the latest commit?

**Comment by Naveennavik** [comment]
Thanks for replying,I'm using latest commit only .
Can i use the test to work on my own dataset?

**Comment by chenwydj** [comment]
You can learn how to write your own dataset by following [BaseDataset.py](https://github.com/TAMU-VITA/FasterSeg/blob/master/tools/datasets/BaseDataset.py) and [cityscapes.py](https://github.com/TAMU-VITA/FasterSeg/blob/master/tools/datasets/cityscapes/cityscapes.py).

**Comment by Naveennavik** [comment]
In BaseDataset.py main these are the line i need to give path right?
img_root=is the path to the image folder 
whereas train_source and eval_source is what may i know
Big Thanks in advance
data_setting = {'img_root': '',
                    'gt_root': '',
                    'train_source': '',
                    'eval_source': ''}

**Comment by chenwydj** [comment]
Please follow this [configuration file](https://github.com/TAMU-VITA/FasterSeg/blob/master/train/config_train.py#L29).

**Comment by Naveennavik** [comment]
For the new dataset we need train and then only we can test right orelse we can directly run test code?
I dont understand clearly on the documentation how to run ?

**Comment by chenwydj** [comment]
If your dataset is very different from Cityscapes (e.g. different number of semantic classes, large appearance gap), then yes, you first need to train on your dataset, then evaluate.

**Comment by Naveennavik** [comment]
cityscapes_train_fine.txt
cityscapes_train_val_fine.txt
cityscapes_val_fine.txt
cityscapes_test.txt
How to prepare these txt files for further process

**Comment by chenwydj** [comment]
You can just use python to list all the file names and write them into a file with the same format.
