### ISSUE TITLE
 symbol lookup error： undefined symbol：PySlice_Unpack

### ISSUE THREAD

**Issue by oym1994** [TAMU-VITA/FasterSeg#15]
您好，麻烦您在ReadMe里补充说明python3的具体版本，我查了以下这个问题，PySlice_Unpack在python3.6.1才被引入，解决办法是使用python3.6.2，我之前用的python3.6.0旧遇到这个bug。希望更严谨一些，其他环境配置要求也希望如此完善一下，谢谢。

**Comment by chenwydj** [comment]
Thank you @oym1994 !

I have just updated detailed prerequisites in Readme.

**Comment by oym1994** [comment]
Thank you very much！！
