### ISSUE TITLE
Head: Paper vs Code

### ISSUE THREAD

**Issue by theevann** [TAMU-VITA/FasterSeg#16]
Hello !

In the paper, the heads are fairly clearly defined with the picture.

In your code, I see that and I don't exactly understand what this is for :

![image](https://user-images.githubusercontent.com/3309183/75558620-5e9e5e80-5a42-11ea-805d-e041d7b67153.png)

**Comment by chenwydj** [comment]
Hi @theevann ! Thank you for your interest!

In https://github.com/TAMU-VITA/FasterSeg/blob/master/search/model_search.py:
Line 338 ~ 344: progressive feature aggregation (orange dashed rectangular in paper).
Line 346 ~ 350: final projection layer for pixel-wise classification.
