### ISSUE TITLE
Why do you weight latencies from different scales differently?

### ISSUE THREAD

**Issue by maaft** [TAMU-VITA/FasterSeg#20]
In your code you weight the latency coming from each branch differently with 
```python
scale_latency_weights=[3./12, 4./12, 5./12]
```
in:
https://github.com/TAMU-VITA/FasterSeg/blob/bb52a004ff83f64d3dd8989104234fdb862d1cc5/search/model_search.py#L474

Can you elaborate on why you do this?

**Comment by chenwydj** [comment]
Hi @maaft ! I just updated the repo. You don't have to use this weight.
