### ISSUE TITLE
Error about TensorRT and Pycuda

### ISSUE THREAD

**Issue by NoOneUST** [TAMU-VITA/FasterSeg#26]
When I run CUDA_VISIBLE_DEVICES=1 python train_search.py, I get this
/export/data/lwangcg/FasterSeg/tools/utils/darts_utils.py:179: UserWarning: TensorRT (or pycuda) is not installed. compute_latency_ms_tensorrt() cannot be used.
  warnings.warn("TensorRT (or pycuda) is not installed. compute_latency_ms_tensorrt() cannot be used.")

I have tried to install Pycuda and TensorRT, but I might did not do it successfully. I get a warning in Pycuda test and fail in TensorRT test. Can you kindly help me with this? Note, I have no root privilege to the system(Centos 7)

FasterSeg:
![image](https://user-images.githubusercontent.com/48406286/77541397-9680b080-6edf-11ea-8cb5-bcdfd7003b9b.png)

TensorRT:
![image](https://user-images.githubusercontent.com/48406286/77541856-40603d00-6ee0-11ea-9f64-f176203aa852.png)

Pycuda:
![image](https://user-images.githubusercontent.com/48406286/77541897-53730d00-6ee0-11ea-9789-5d9c09b668ad.png)

**Comment by chenwydj** [comment]
Hi @NoOneUST !

Please kindly refer to [TensorRT doc](https://docs.nvidia.com/deeplearning/sdk/tensorrt-install-guide/index.html) and [TensorRT github repo](https://github.com/NVIDIA/TensorRT) for installation issues. Thank you!
