### ISSUE TITLE
What is the difference between arch and model? Why should we have them both?

### ISSUE THREAD

**Issue by NoOneUST** [TAMU-VITA/FasterSeg#27]

**Comment by NoOneUST** [comment]
Another Question, when I try to use multi-process-evaluation, no matter I input device=[3,5,6,7] or [0,1,2,3] when CUDA_VISIBLE_DEVICES=3,5,6,7. The occupied GPUs are always 0,1,2,3. How should I solve it?
![image](https://user-images.githubusercontent.com/48406286/77666222-a7065900-6fbb-11ea-8266-9150a289fa11.png)

**Comment by chenwydj** [comment]
Hi @NoOneUST!

Thank you for your interest in our work!

The differentiable NAS formulate the search space as the model (e.g. convolution weights) and architecture (determines which operator to use in each cell). During the search, the model parameters and the architecture parameters are alternatively optimized. Thus, we need both of them.

To enable the multi-gpu training, you have to at least wrap the `nn.Module` into `nn.DataParallel` (which I did not implement here).
