### ISSUE TITLE
The inference speed is too slow

### ISSUE THREAD

**Issue by haezu** [TAMU-VITA/FasterSeg#29]

**Comment by haezu** [comment]
Hi. Thank you for releasing the code for the paper. 
After completing the training, we measured the execution time in the process of testing. But the execution speed is too slow. How do I get the results out of your thesis? What is the problem?

```
def whole_eval(self, img, output_size, input_size=None, device=None):

        if input_size is not None:
            start = time.perf_counter()
            img, margin = self.process_image(img, input_size)
            end = time.perf_counter()
            print('preprocessing :', end-start, 'seconds')

        else:
            img = self.process_image(img, input_size)

        start = time.perf_counter()

        pred = self.val_func_process(img, device)

        if input_size is not None:
            pred = pred[:, margin[0]:(pred.shape[1] - margin[1]),
                   margin[2]:(pred.shape[2] - margin[3])]
        
        pred = pred.permute(1, 2, 0)
        pred = pred.cpu().numpy()
        if output_size is not None:
            pred = cv2.resize(pred,
                              (output_size[1], output_size[0]),
                              interpolation=cv2.INTER_LINEAR)

        pred = pred.argmax(2)
        end = time.perf_counter()
        print('prediction :', end-start, 'seconds')

        return pred
```

![image](https://user-images.githubusercontent.com/46044118/78103868-ed7b0e00-7428-11ea-8332-fbff5554b10e.png)

**Comment by ashkanaev** [comment]
Hi! 
I've measured the same latency ~120ms for student model.
Have no idea how to archive stated FPS with pretrained model.. Is't possible? 
Maybe i've missed something?
Thanks!

@chenwydj

**Comment by chenwydj** [comment]
Hi @haezu!

Thank you for your interest in our work!

If you set `C.is_test = True` in the configure file, then the prediction file (which can be uploaded to Cityscapes official leaderboard) will be generated, which makes the test slow. These files (.png) are saved under the `prediction` directory.

If you just evaluate on the evaluation set (`C.is_eval`) it is fast.
