### ISSUE TITLE
Getting lower mIOU than reported in paper

### ISSUE THREAD

**Issue by soyebn** [TAMU-VITA/FasterSeg#32]
One of the best works for semantic seg with NAS. Thank You for sharing train as well as search code.

I downloaded student's weights from the location mentioned in the readme https://drive.google.com/file/d/1O56HnA0ug2M3K4SR3_AUzIs0wegy9BX6/view?usp=sharing and ran train.py to check the validation accuracy but I got 70.5%.
But your paper suggest it should generate 73.1%. Am I doing something wrong?

Thanks.

**Comment by chenwydj** [comment]
Hi @soyebn!

Thank you for your interest in our work!

73.1% is the best achievable validation performance during the training. The provided checkpoint is from the last epoch. It should give you similar results with our code.
