### ISSUE TITLE
inference speed

### ISSUE THREAD

**Issue by yyfyan** [TAMU-VITA/FasterSeg#4]
Can you provide some compare about TensorRT and Pytorch at inference speed? thanks.

**Comment by chenwydj** [comment]
For our searched architecture (FasterSeg):
TensorRT: 163.9 FPS
Pytorch: 89.8 FPS

**Comment by yyfyan** [comment]
OK, thanks.
TensorRT can process arbitrary pytorch model?

**Comment by chenwydj** [comment]
I think Pythorch supports more layer types and configurations. But for most common layer's, yes TensorRT does support.

**Comment by zhangyunming** [comment]
in the compare list ,does fast scnn or else use tensorrt?

**Comment by chenwydj** [comment]
- ENet, ICNet, CAS, Fast-SCNN: they did not release their code for latency.
- BiSeNet: They released their code. I can reproduce their FPS using TensorRT (but not with Pytorch).
- DF1-Seg-d8 (Li et al., 2019): yes they used TensorRT.

More works used TensorRT:
- SpineNet: Learning Scale-Permuted Backbone for Recognition and Localization.
- Pelee: A Real-Time Object Detection System on Mobile Devices.
- IRLAS: Inverse Reinforcement Learning for Architecture Search.

**Comment by lxtGH** [comment]
@zhangyunming fast scnn use the TensorRT and its pytorch speed is only 70+ FPS

**Comment by chenwydj** [comment]
@lxtGH Where did you find this? I did not see this in Fast-SCNN paper.

**Comment by lxtGH** [comment]
@chenwydj  I email to the author and also I test it in my implementation.

**Comment by chenwydj** [comment]
@lxtGH Thanks for sharing the info!

**Comment by lxtGH** [comment]
@chenwydj Could you share your speed on Camvid and BDD without using the Tensor-RT ??

**Comment by chenwydj** [comment]
@lxtGH Pytorch version FPS
CamVid (720x960): 131.8
BDD (720x1280): 127.3
