### ISSUE TITLE
如何用自己的数据来训练这个模型？

### ISSUE THREAD

**Issue by oym1994** [TAMU-VITA/FasterSeg#6]
您好！这个模型的高性能高效率非常棒，我打算在我的研究项目中用它来做道路分割，但我在这方面没有研究过，暂时只想将算法应用起来，请问后期可以出一个“如何从自己的原始图片数据集来训练该网络”的教程吗？给只想应用的后来者们一个清晰的指导，谢谢啦

**Comment by chenwydj** [comment]
如果要用自己的数据的话:
1. 需要准备自己的RGB images和ground truth label (具体文件格式可参考[Cityscapes](https://www.cityscapes-dataset.com/downloads/)).
2. 准备dataset files用来load data (see [examples here]( https://github.com/TAMU-VITA/FasterSeg/tree/master/tools/datasets)).
3. `num_classes`参数需要调整为您需要预测的类别数量 (in [configuration file](https://github.com/TAMU-VITA/FasterSeg/blob/master/search/config_search.py#L40)).

**Comment by oym1994** [comment]
非常感谢！！！
