### ISSUE TITLE
Could I use the search result to train model directly ?

### ISSUE THREAD

**Issue by nieyan** [TAMU-VITA/FasterSeg#8]
Thank you for your great work!!!  Search process may take a long time to run.  Want use the citysacpe dataset search result model to train my own data at first. But I can't find that code.

**Comment by chenwydj** [comment]
Thank you for your interest in our work!

1. You need to provide the dataloader for your data (see [examples here]( https://github.com/TAMU-VITA/FasterSeg/tree/master/tools/datasets)).
2. The current provided training configuration file is already using the [searched architecture from Cityscapes](https://github.com/TAMU-VITA/FasterSeg/tree/master/train/fasterseg). So you can use the provided [training code](https://github.com/TAMU-VITA/FasterSeg/tree/master/train) to train on your data with our searched model.
3. One thing you may need to be aware of is that your `num_classes ` equals to that of Cityscapes which is 19.
