### ISSUE TITLE
Runtime error: Cuda error:out of memory

### ISSUE THREAD

**Issue by riazspace** [TAMU-VITA/FasterSeg#9]
Hi 
Thanks for sharing your nice work. i have found an issue while using your code for training on my Nvidia GTX 1080 ti card. 
Can you please help me about this issue?

The issue is 

when i run train_search.py it generate the Runtime Error. The error pic is attached 
![Screenshot from 2020-01-16 14-22-52](https://user-images.githubusercontent.com/4491902/72525951-20305400-3887-11ea-926b-eb4b407191c8.png)

**Comment by chenwydj** [comment]
As it says, the GPU card you are using is running out of its graphic memory.

Check if you have multiple jobs on one card. If not, you could turn down the batch size or crop size to reduce the GPU memory usage.

**Comment by TamuseDomain** [comment]
Hi, @riazspace 
I would like to know if you were able to run. I'm trying with GeForce GTX 1650 but I get a similar error as your screenshot:

![image](https://user-images.githubusercontent.com/30960795/104520391-4979e200-55b8-11eb-872b-6cceead81bc4.png)

I already tried turning down the batch size, crop size and even the number of workers.
Will the GeForce be able to run this work, or do I need a more capable GPU?
